// <auto-generated />
using System;
using CarRentalApp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarRentalApp.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260217155719_AddAllEntitiesWithRolesUpdated")]
    partial class AddAllEntitiesWithRolesUpdated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarRentalApp.Domain.Entities.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerDay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearOfProduction")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Toyota",
                            CategoryId = 1,
                            IsAvailable = true,
                            Mileage = 15000,
                            Model = "Corolla",
                            PricePerDay = 50.00m,
                            RegistrationNumber = "ABC123",
                            YearOfProduction = 2022
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Honda",
                            CategoryId = 1,
                            IsAvailable = true,
                            Mileage = 8000,
                            Model = "Civic",
                            PricePerDay = 55.00m,
                            RegistrationNumber = "DEF456",
                            YearOfProduction = 2023
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Ford",
                            CategoryId = 2,
                            IsAvailable = true,
                            Mileage = 25000,
                            Model = "Explorer",
                            PricePerDay = 85.00m,
                            RegistrationNumber = "GHI789",
                            YearOfProduction = 2021
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Jeep",
                            CategoryId = 2,
                            IsAvailable = true,
                            Mileage = 18000,
                            Model = "Grand Cherokee",
                            PricePerDay = 90.00m,
                            RegistrationNumber = "JKL012",
                            YearOfProduction = 2022
                        },
                        new
                        {
                            Id = 5,
                            Brand = "BMW",
                            CategoryId = 3,
                            IsAvailable = true,
                            Mileage = 5000,
                            Model = "5 Series",
                            PricePerDay = 150.00m,
                            RegistrationNumber = "MNO345",
                            YearOfProduction = 2023
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Mercedes-Benz",
                            CategoryId = 3,
                            IsAvailable = false,
                            Mileage = 3000,
                            Model = "E-Class",
                            PricePerDay = 160.00m,
                            RegistrationNumber = "PQR678",
                            YearOfProduction = 2023
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Porsche",
                            CategoryId = 4,
                            IsAvailable = true,
                            Mileage = 1000,
                            Model = "911",
                            PricePerDay = 250.00m,
                            RegistrationNumber = "STU901",
                            YearOfProduction = 2024
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Mercedes-Benz",
                            CategoryId = 5,
                            IsAvailable = true,
                            Mileage = 40000,
                            Model = "Sprinter",
                            PricePerDay = 100.00m,
                            RegistrationNumber = "VWX234",
                            YearOfProduction = 2021
                        });
                });

            modelBuilder.Entity("CarRentalApp.Domain.Entities.CarPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("CarPhotos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarId = 1,
                            IsMain = true,
                            PhotoUrl = "/images/cars/toyota-corolla-1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            CarId = 1,
                            IsMain = false,
                            PhotoUrl = "/images/cars/toyota-corolla-2.jpg"
                        },
                        new
                        {
                            Id = 3,
                            CarId = 2,
                            IsMain = true,
                            PhotoUrl = "/images/cars/honda-civic-1.jpg"
                        },
                        new
                        {
                            Id = 4,
                            CarId = 3,
                            IsMain = true,
                            PhotoUrl = "/images/cars/ford-explorer-1.jpg"
                        },
                        new
                        {
                            Id = 5,
                            CarId = 4,
                            IsMain = true,
                            PhotoUrl = "/images/cars/jeep-grandcherokee-1.jpg"
                        },
                        new
                        {
                            Id = 6,
                            CarId = 5,
                            IsMain = true,
                            PhotoUrl = "/images/cars/bmw-5series-1.jpg"
                        },
                        new
                        {
                            Id = 7,
                            CarId = 6,
                            IsMain = true,
                            PhotoUrl = "/images/cars/mercedesbenz-eclass-1.jpg"
                        },
                        new
                        {
                            Id = 8,
                            CarId = 7,
                            IsMain = true,
                            PhotoUrl = "/images/cars/porsche-911-1.jpg"
                        },
                        new
                        {
                            Id = 9,
                            CarId = 8,
                            IsMain = true,
                            PhotoUrl = "/images/cars/mercedesbenz-sprinter-1.jpg"
                        });
                });

            modelBuilder.Entity("CarRentalApp.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Affordable and fuel-efficient cars.",
                            Name = "Economy"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Spacious and comfortable SUVs.",
                            Name = "SUV"
                        },
                        new
                        {
                            Id = 3,
                            Description = "High-end and premium vehicles.",
                            Name = "Luxury"
                        },
                        new
                        {
                            Id = 4,
                            Description = "High-performance sports cars.",
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Large capacity vans for groups.",
                            Name = "Van"
                        });
                });

            modelBuilder.Entity("CarRentalApp.Domain.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DriverLicense")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DriverLicense = "DL123456",
                            FirstName = "John",
                            LastName = "Doe",
                            UserId = "user-customer-id"
                        },
                        new
                        {
                            Id = 2,
                            DriverLicense = "DL345678",
                            FirstName = "Worker",
                            LastName = "Worker",
                            UserId = "user-worker-id"
                        },
                        new
                        {
                            Id = 3,
                            DriverLicense = "DL901234",
                            FirstName = "Admin",
                            LastName = "Admin",
                            UserId = "user-admin-id"
                        });
                });

            modelBuilder.Entity("CarRentalApp.Domain.Entities.Rental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RentalDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("ClientId");

                    b.ToTable("Rentals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarId = 6,
                            ClientId = 1,
                            IsPaid = true,
                            RentalDate = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            TotalCost = 800.00m
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "role-user-id",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "role-worker-id",
                            Name = "Worker",
                            NormalizedName = "WORKER"
                        },
                        new
                        {
                            Id = "role-admin-id",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "user-customer-id",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "99f136fd-471e-4680-a213-312d429a5a8c",
                            Email = "customer@carrental.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "CUSTOMER@CARRENTAL.COM",
                            NormalizedUserName = "CUSTOMER@CARRENTAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMuZB6LOnyNbjX0RsfzbsqhGC7kfFcGHZ98qGzytb30y9LSfmacjqEjDwaH4Be3a0Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "778b368a-f0be-4a3b-9658-e8c904b65790",
                            TwoFactorEnabled = false,
                            UserName = "customer@carrental.com"
                        },
                        new
                        {
                            Id = "user-worker-id",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d843e46c-a1ef-4132-acf0-8613c219cb8c",
                            Email = "worker@carrental.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "WORKER@CARRENTAL.COM",
                            NormalizedUserName = "WORKER@CARRENTAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGrXp7/+4ikjSIux2nB5uE5SSfXwVVxbTUg0t1CMoVasznaFobcE9EF+fN0HvyO4BA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2b16075d-9530-44e3-934f-9570bf824b87",
                            TwoFactorEnabled = false,
                            UserName = "worker@carrental.com"
                        },
                        new
                        {
                            Id = "user-admin-id",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b0dec909-37b8-4af6-ae4b-536225cf501b",
                            Email = "admin@carrental.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@CARRENTAL.COM",
                            NormalizedUserName = "ADMIN@CARRENTAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFSBzWF6JqaL96jkP3j2I0hOPlnED8peMihyYYJTu+zPmb992qufF8ZZuj39Q4f3dg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f7f36521-4238-4e5f-a1f2-9e80dc03526a",
                            TwoFactorEnabled = false,
                            UserName = "admin@carrental.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "user-customer-id",
                            RoleId = "role-user-id"
                        },
                        new
                        {
                            UserId = "user-worker-id",
                            RoleId = "role-worker-id"
                        },
                        new
                        {
                            UserId = "user-admin-id",
                            RoleId = "role-admin-id"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CarRentalApp.Domain.Entities.Car", b =>
                {
                    b.HasOne("CarRentalApp.Domain.Entities.Category", "Category")
                        .WithMany("Cars")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CarRentalApp.Domain.Entities.CarPhoto", b =>
                {
                    b.HasOne("CarRentalApp.Domain.Entities.Car", "Car")
                        .WithMany("CarPhotos")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("CarRentalApp.Domain.Entities.Client", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithOne()
                        .HasForeignKey("CarRentalApp.Domain.Entities.Client", "UserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("CarRentalApp.Domain.Entities.Rental", b =>
                {
                    b.HasOne("CarRentalApp.Domain.Entities.Car", "Car")
                        .WithMany("Rentals")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarRentalApp.Domain.Entities.Client", "Client")
                        .WithMany("Rentals")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarRentalApp.Domain.Entities.Car", b =>
                {
                    b.Navigation("CarPhotos");

                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("CarRentalApp.Domain.Entities.Category", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("CarRentalApp.Domain.Entities.Client", b =>
                {
                    b.Navigation("Rentals");
                });
#pragma warning restore 612, 618
        }
    }
}
